[tool.poetry]
name = "hazm"
version = "0.0.9"
description = "Persian NLP Toolkit"
authors = ["Roshan <salam@roshan-ai.com>"]
maintainers = ["Roshan <salam@roshan-ai.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://roshan-ai.ir/hazm/"
repository = "https://github.com/roshan-research/hazm/"
documentation = "https://roshan-ai.ir/hazm/docs/"
keywords = ["nlp", "persian nlp", "persian"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Text Processing",
    "Natural Language :: Persian",
]
include = ["data/*"]

[tool.poetry.dependencies]
python="^3.6"
nltk="^3.8.1"
gensim="^4.1.2"
numpy="^1.19.5"
python-crfsuite="^0.9.9"

[tool.poetry.group.docs]
optional=true

[tool.poetry.group.docs.dependencies]
mkdocs="^1"
mkdocstrings="^0"
mkdocs-material="^8"
mkdocs-glightbox="^0"
pymdown-extensions="^9"

[tool.poetry.urls]
"Demo" = "https://www.roshan-ai.ir/hazm/demo/"
"Changelog" = "https://github.com/roshan-research/hazm/blob/master/CHANGELOG.md"
"Contribution" = "https://github.com/roshan-research/hazm/blob/master/CONTRIBUTION.md"
"Issues" = "https://github.com/roshan-research/hazm/issues"
"JoinUs" = "https://www.roshan-ai.ir/join-us/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
